# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 28 Jan 2018 17:39:27 +0000
*	@ALL	1
*	@user	1
admin:*	@ALL	0
admin:*	@user	0
