<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: bobziemerman
 * Date: Thu, 01 Apr 2021 16:00:12 -0500
 */

$conf['title'] = 'The Sage Vault';
$conf['start'] = 'home';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin,bobziemerman';
$conf['disableactions'] = 'recent,search,register,rss,subscribe,unsubscribe';
$conf['htmlok'] = 1;
$conf['sitemap'] = 30;
$conf['sepchar'] = '-';
$conf['autoplural'] = 1;
$conf['gzip_output'] = 1;
$conf['jquerycdn'] = 'jquery';
