<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: bobziemerman
 * Date: Wed, 14 Nov 2018 15:27:16 -0600
 */

$conf['title'] = 'Dracarcer';
$conf['start'] = 'home';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin,bobziemerman';
$conf['disableactions'] = 'recent,search,register,rss,subscribe,unsubscribe';
$conf['htmlok'] = 1;
$conf['sitemap'] = 30;
$conf['sepchar'] = '-';
$conf['autoplural'] = 1;
$conf['gzip_output'] = 1;
$conf['jquerycdn'] = 'jquery';

// end auto-generated content
